### ISSUE TITLE
Current nuget package is older than the previous version

### ISSUE THREAD

**Issue by slang25** [fsprojects/FSharp.Collections.ParallelSeq#12]
According to nuget.org, [this package](https://www.nuget.org/packages/FSharp.Collections.ParallelSeq/) is at version 1.0.2, however version 1.0.1 was published later, and is more reflective of the current master branch, in particular Profile7 support.

Could a new package version be released to prevent future confusion.

**Comment by jamessdixon** [comment]
a new package version was released
