### ISSUE TITLE
Methods not found with most recent nuget package

### ISSUE THREAD

**Issue by ErikApption** [fsprojects/FSharp.Collections.ParallelSeq#13]
### Description

With package 1.0.2 there is an issue with the execution of FSharp programs. I do get
`Method not found: 'Void FSharp.Collections.ParallelSeq.PSeqModule.<method>` for all PSeq.methods

This is really strange, I can dissemble the nuget dll and see the functions, the compilation is ok. This used to work and I suspect it is the update of FSharp.Core to 4.4.1.0 that broke the execution. There is no dll loading error in fusion logs.
Also just adding the PSeq source code to my projects did solve the issue but it is ugly.

`
 TestBinsManagerStatusUpdate : System.MissingMethodException : Method not found: 'Void FSharp.Collections.ParallelSeq.PSeqModule.iter(Microsoft.FSharp.Core.FSharpFunc`2<!!0,Microsoft.FSharp.Core.Unit>, System.Collections.Generic.IEnumerable`1<!!0>)'.
   at Apption.MailReader.DataInterfaces.BinsManager.Close()
   at Apption.MailReader.DataInterfaces.BinsManager.Stop() in F:\code\ParallelMailParser\MailParserLibrary\BinsManager.fs:line 199
   at RegressionTest.EndToEndTesting.TestBinsManagerStatusUpdate() in F:\code\ParallelMailParser\RegressionTest\UnitTest1.cs:line 638
`

### Related information 

* Operating system: Win 10
* .NET Runtime, CoreCLR or Mono Version: .NET 4.6

**Comment by dsyme** [comment]
Do you have an appropriate binding redirect for FSharp.Core?  Perhaps share a zip?

**Comment by ChrSteinert** [comment]
Should be done with the latest NuGet, right?
