### ISSUE TITLE
Library is not parallelizing on Azure Notebooks

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/FSharp.Collections.ParallelSeq#14]
### Description
The Library appears to not use mutliple cores when using Azure Notebooks

### Repro steps
1. Log into Azure Notebooks
2. Clone my Library: http://bit.ly/fspydata
3. Open the Notebook entitled parallelSeq.ipynb
4. Run the parallel example:  note that the sequental and the parallel runs are roughly equal
5. Run the processor count example:  note the processor count is 8

*running this same code on my local machine returns the expected result:  parallel is much faster than serial

### Expected behavior

parallel should be faster. 

### Actual behavior

it is not

### Known workarounds

None

### Related information 

* Operating system: Linux 
* Branch (??)
* .NET Runtime, CoreCLR or Mono Version (??)
* Performance information, links to performance testing scripts see above

Not sure if it is a Linux issue or a Azure Notebooks issue?

**Comment by dsyme** [comment]
Maybe Azure Notebooks is using docker virtualized onto a server in a single-cpu way?

**Comment by jamessdixon** [comment]
Has the lib been tested with Linux so we know that Linux isn't causing the problem?

**Comment by dsyme** [comment]
@jamessdixon I'm pretty sure the Mono implementation nowadays uses the same implementation as .NET.  But I'm also pretty sure the docker containers you're getting for free on Azure Notebooks are not multi-processor enabled?

**Comment by cgravill** [comment]
Some timing numbers:

Windows desktop:
```
serial: 00:00:03.7483724
parallel: 00:00:01.7584048
parallel(2): 00:00:01.8222855

8 (System.Environment.ProcessorCount)
```
parallel(2) I've tried to control the parallelism with:
```fsharp
nums 
|> PSeq.filter isPrime
|> PSeq.groupBy (fun i -> i % 10)
|> PSeq.map (fun (k, vs) -> (k, Seq.length vs))
|> PSeq.toArray
|> PSeq.withDegreeOfParallelism 2
```

Azure Notebook:

```
serial: 00:00:08.8649760
parallel: 00:00:08.3356960

2 (System.Environment.ProcessorCount)
```

MacOS:

(collecting)

**Comment by cgravill** [comment]
I extended the computation by 10x and on Azure Notebooks I got this:

```
serial: 00:03:56.9091570
parallel: 00:04:23.0780800
parallel(2): 00:04:24.4262670
```

I suspect what you're actually testing is stressing the memory system causing sub-linear scaling. That gives the impression of not using more cores. In your prime test there's a lot of allocation/deallocation happening. When I repeat with the same numbers but this adjusted prime function

```fsharp
let isPrime n = 
    let upperBound = int (sqrt (float n))
    let hasDivisor =     
        seq {2..upperBound}
        |> Seq.exists (fun i -> n % i = 0)
    not hasDivisor
```
then I get nicer scaling:

```
serial: 00:00:09.9083290
parallel: 00:00:06.3737730
parallel(2): 00:00:06.1310710
```

I didn't use it here but I strongly recommend https://github.com/dotnet/BenchmarkDotNet as it has some really robust defaults around repeated runs and warm-up. Many of the above measurements have significant variability and may confuse matters.

**Comment by jamessdixon** [comment]
it looks like the problem is on Azure side and not FSharp.Collections.Parallel Side
