### ISSUE TITLE
Can't upgrade to 1.1.0

### ISSUE THREAD

**Issue by jimfoye** [fsprojects/FSharp.Collections.ParallelSeq#27]
I'm still using VS 2015, targeting 4.6.2, which can't change anytime soon.

Upgrading from 1.0.2 to 1.1.0 results in warning MSB3277, "Found conflicts between different versions of the same dependent assembly...". I guess I'm stuck on 1.0.2 for now?

**Comment by dsyme** [comment]
Which assembly has the conflict?  Are you using AutoGenerateBindingRedirects in your project? See https://fsharp.github.io/2015/04/18/fsharp-core-notes.html

Also, it might be that the lack of a "dependency" node in the nuget package is causing problems, as it is not clarifying the version of FSharp.Core it depends on.  Version 1.1.2 of the package has now been fixed clarifying this

**Comment by dsyme** [comment]
Also, Version 1.1.2 of the package explicitly uses 
* FSharp.Core 4.0.0.0 as the minimal dependency for .NET 4.5, 
* FSharp.Core 4.4.3.0 as the minimal dependency for .NET Standard 2.0 (which you aren't using).  

That might help.

**Comment by dsyme** [comment]
I'll close as I'm sure one of these things are the issue

**Comment by jimfoye** [comment]
Upgrading to 1.1.2 fixes the problem for me. Thank you.
