### ISSUE TITLE
Package authors not listed correctly

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Collections.ParallelSeq#30]
The package authors are not listed correctly. This should be any of
* "F# Community contributors"  or
* "F# Incubation Space Contributors (fsprojects)" or
* the maintainers of the package

At the moment it just says this:

![image](https://user-images.githubusercontent.com/7204669/40812059-d1ee5718-652b-11e8-962f-ae91435d84c6.png)

**Comment by jamessdixon** [comment]
Closing as it was fixed about 2 years ago
