### ISSUE TITLE
Licence in nuget

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Collections.ParallelSeq#33]
A message on nuget:

> For some reason version 1.1.1 and 1.1.2 of FSharp.Collections.ParallelSeq don't specify the license like e.g. version 1.1.0 does. Can you please check this?
> https://www.nuget.org/packages/FSharp.Collections.ParallelSeq/1.1.0 
> https://www.nuget.org/packages/FSharp.Collections.ParallelSeq/1.1.1 
> https://www.nuget.org/packages/FSharp.Collections.ParallelSeq/1.1.2
> Thank you!

> Regards Tomas Benak

**Comment by dsyme** [comment]
cc @ChrSteinert @jamessdixon @kapilash

Could anyone take a look, and indeed if possible push a v1.0 version of this packge too?  The package is highly stable and no reason not to do it.

**Comment by ChrSteinert** [comment]
Let me have a look :)

**Comment by ChrSteinert** [comment]
Hey @dsyme – can you just say yay or nay to the PR? :)
