### ISSUE TITLE
Documentation site returns HTTP 404

### ISSUE THREAD

**Issue by pkese** [fsprojects/FSharp.Collections.ParallelSeq#38]
http://fsprojects.github.io/FSharp.Collections.ParallelSeq/ doesn't work.

**Comment by jrr** [comment]
Here's an example of another project's working documentation site:

https://fsprojects.github.io/FSharp.Text.RegexProvider/

It's driven by the `gh-pages` branch of the git repo: https://github.com/fsprojects/FSharp.Text.RegexProvider/tree/gh-pages

So I think to fix ParallelSeq's doc page, it'd be necessary to build the docs (run [generate.fsx](https://github.com/fsprojects/FSharp.Collections.ParallelSeq/blob/master/docs/tools/generate.fsx)?) and push them up to a `gh-pages` branch.

**Comment by dsyme** [comment]
This is fixed - the build is updated and now auto-published nuget and docs

http://fsprojects.github.io/FSharp.Collections.ParallelSeq/
