### ISSUE TITLE
PSeq.exists2 occasionally is incorrect

### ISSUE THREAD

**Issue by mydogisbox** [fsprojects/FSharp.Collections.ParallelSeq#5]
The following will occasionally return false:

```
open System
open System.Linq
open System.Threading

type pseq<'T> = ParallelQuery<'T>

let inline toP (s : seq<'T>) = 
    match s with
    | null -> nullArg "s"
    | :? pseq<'T> as p ->  p
    | _ -> s.AsParallel()    

let exists2 (f : 'T -> 'U -> bool) s1 s2 = 
    ParallelEnumerable.Any(ParallelEnumerable.Zip(toP(s1), toP(s2),Func<_,_,_>(f)), Func<_,_>(id))

let funcInt x y = (x+y)%3=0 
let Intexists2Seq1 =  seq [1;3;7]
let Intexists2Seq2 = seq [1;6;3]

exists2 funcInt Intexists2Seq1 Intexists2Seq2
```

**Comment by mydogisbox** [comment]
Fixed by https://github.com/fsprojects/FSharp.Collections.ParallelSeq/pull/6

**Comment by mydogisbox** [comment]
I should have made a note.  There was a problem with the fix, so I rolled it back.

**Comment by dsyme** [comment]
Ah ok, thanks!

**Comment by mydogisbox** [comment]
@forki @pblasucci Maybe one of you can help me with this.  I tracked down the cause of the issue (finally had a couple free days).  The reason `exists2` occasionally returns false is that `IEnumerable.AsParallel` will wrap an enumerable as a parallel enumerable which assumes the elements of the enumerable is _unordered_.   See [here](https://msdn.microsoft.com/en-us/library/dd460677(v=vs.110).aspx) for details.  

Assuming we want pseq to have the same semantics as `ParallelEnumerable`, I think this means that the test is incorrect.  In order for `PSeq` to work the same as `ParallelEnumerale` we'll need to add a couple methods something like this:

    let asOrdered = toP >> ParallelEnumerable.AsOrdered
    let asUnordered = toP >> ParallelEnumerable.AsUnordered

and then change the test from [this ](https://github.com/fsprojects/FSharp.Collections.ParallelSeq/blob/master/tests/FSharp.Collections.ParallelSeq.Tests/Tests.fs#L1905) to something like this (this isn't the only test which will need to be updated):

    // string Seq
    let resultStr = PSeq.zip (seq ["str3";"str4"] |> PSeq.asOrdered) (seq ["str1";"str2"] |> PSeq.asOrdered)
    let expectedStr = seq ["str3","str1";"str4","str2"]
    VerifyPSeqsEqual expectedStr resultStr

Additionally, I will add some notes in the examples and documentation so the semantics are more obvious.

If that is amenable to everyone, I will write something up and create a PR for review.

**Comment by dsyme** [comment]
@mydogisbox Yes, this makes sense.

**Comment by dsyme** [comment]
I've updated the integer case of this test as well
