### ISSUE TITLE
Enable travis and AppVeyor on repo

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Collections.ParallelSeq#8]
Hi all

For some reason no Travis or AppVeyor CI builds are enabled on this repo - could we enable those?  It should just be a matter of adding the .travis.yml and appveyor.yml files and registering the repos with the services.

cheers
don

**Comment by mydogisbox** [comment]
I will take a look when I get some free time.

**Comment by mydogisbox** [comment]
@dsyme  https://github.com/fsprojects/FSharp.Collections.ParallelSeq/pull/9
I addd the build files, but the travis CI build is failing for some reason.  Also, do I need to register the repo with appveyor in some way for that build to run?
